Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Breadlesscode.SimpleEditorExtend:UiPlugin':
            resource: resource://Breadlesscode.SimpleEditorExtend/Public/UiPlugin/Plugin.js
      frontendConfiguration:
        'Breadlesscode.SimpleEditorExtend':
          'Test.Test:MyCustomSpan':
            extensionName: 'exampleExtension'
            icon: 'plus-square'
            tooltip: 'Mark the text in color green'
            position: 'before strong'
            formatting:
              tag: 'span'
              classes: 'test-class'
              styles:
                background-color: 'green'
          'Test.Test:MyCustomSpan2':
            extensionName: 'exampleExtension2'
            icon: 'rocket'
            tooltip: 'Mark the text in color red'
            position: 'before exampleExtension'
            formatting:
              tag: 'span'
              classes: 'test-class-2'
              styles:
                background-color: 'red'

  Flow:
    mvc:
      routes:
        'Breadlesscode.SimpleEditorExtend': 
          position: 'start'
